version: '3'
services:
    uib:
        container_name: uib
        build: 'UIBackend/'
        ports:
            - 3000:3000
        volumes:
            - ./UIBackend:/usr/src/app
        networks:
            - cache-net
        depends_on:
            - redis
    casey:
        container_name: casey
        build: Casey/
        ports:
            - 3001:3001
        volumes:
            - ./Casey:/usr/src/app
        networks:
            - cache-net
    redis:
        container_name: redis
        build: Redis/
        ports:
            - 6379:6379
        networks:
            - cache-net
networks:
    cache-net:
        driver: bridge