version: '3'
services:
    ui-backend:
        build: 'UI Backend/'
        ports:
            - 3000:3000
        volumes:
            - UI Backend:/usr/src/app
        links:
            - redis
    casey:
        build: Casey/
        ports:
            - 3001:3001
    redis:
        build: Redis/